name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t visx/tic-tac-toe-server:latest .

      - name: Push Image to Docker Hub
        run: docker push visx/tic-tac-toe-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and remove old container (if any)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Pull latest image from Docker Hub
        run: docker pull visx/tic-tac-toe-server:latest

      - name: Run new container
        run: docker run -d -p 5000:5000 --name nodejs-app-container visx/tic-tac-toe-server:latest
